import type { Metadata } from "next";
import "./globals.scss";
import "./styles/fonts.scss";
import StoreProvider from "./components/StoreProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang="ru">
                <body>{children}</body>
            </html>
        </StoreProvider>
    );
}
